settings:
  default-world: world  # регион по умолчанию
  disabled-worlds: # в случае использование функций в данных мирах, игрок будет перемещён в мир по умолчанию
    - spawn
    - pvp
    - duels

main:
  # enumrtp.safe.use - разрешить использование
  # enumrtp.safe.bypass - обход кулдауна
  safe:
    min-radius: 0  # Минимальная точка координат по модулю от 0 мира
    max-radius: 2500  # Максимальная точка координат по модулю от 0 мира
    allow-water-teleport: false  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 30  # Задержка на использование
    aliases:  # добавление возможности использовать телепорт без открывания меню, например /rtp safe
      - safe
      - safety
    messages:
      successful_teleport: "&6РТП &8> &fВы успешно телепортированы на координаты &6{coordinates}&f."
      block_cooldown: "&6РТП &8> &fВы не можете телепортироваться ещё &6{seconds} сек."
      no_locations: "&6РТП &8> &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &8> &cВы не можете телепортироваться на безопасную телепортацию!"


  # enumrtp.far.use - разрешить использование
  # enumrtp.far.bypass - обход кулдауна
  far:
    min-radius: 2000  # Минимальная точка координат по модулю от 0 мира
    max-radius: 10000  # Максимальная точка координат по модулю от 0 мира
    allow-water-teleport: false  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 60  # Задержка на использование
    aliases:
      - far
    messages:
      successful_teleport: "&6РТП &8> &fВы успешно телепортированы на координаты &6{coordinates}&f."
      block_cooldown: "&6РТП &8> &fВы не можете телепортироваться ещё &6{seconds} сек."
      no_locations: "&6РТП &8> &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &8> &cВы не можете телепортироваться на далёкую телепортацию!"

  # enumrtp.player.use - разрешить использование
  # enumrtp.player.bypass - обход кулдауна
  # enumrtp.player.ignore - запретить телепорт возле игрока
  player:
    min-radius: 50  # Минимальная точка по модулю от игрока
    max-radius: 120  # Максимальная точка координат по модулю от игрока
    allow-water-teleport: true  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    warnings: true  # Включить оповещения, отправляемые игроку, возле которого идёт телепорт
    warning-sound: BLOCK_BARREL_OPEN  # кастомный звук при предупреждении
    min-online: 2  # Минимальный онлайн на сервере для работы
    cooldown-seconds: 300  # Задержка на использование

    aliases:
      - player
      - near
    messages:
      successful_teleport: "&6РТП &8> &fВы успешно телепортированы на координаты &6{coordinates}&f рядом с игроком &6{player}&f."
      block_cooldown: "&6РТП &8> &fВы не можете телепортироваться ещё &6{seconds} сек."
      no_locations: "&6РТП &8> &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &8> &cВы не можете телепортироваться рядом с игроками!"
      warning: "&eВозле вас был телепортирован игрок, будьте осторожны!"


  # enumrtp.base.use - разрешить использование
  # enumrtp.base.bypass - обход кулдауна
  base:
    min-radius: 50  # Минимальная точка по модулю от региона
    max-radius: 150  # Максимальная точка координат по модулю от региона
    allow-water-teleport: true  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 600  # Задержка на использование
    aliases:
      - base
    messages:
      successful_teleport: "&6РТП &8> &fВы успешно телепортированы на координаты &6{coordinates}&f рядом с регионом &6{region_name}&f."
      block_cooldown: "&6РТП &8> &fВы не можете телепортироваться ещё &6{seconds} сек."
      no_locations: "&6РТП &8> &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &8> &cВы не можете телепортироваться рядом с базами!"

################################
######## Создание МЕНЮ #########
################################
# Доступные function:
# close - закрытие инвентаря
# safe - телепортация в режиме safe
# far - телепортация в режиме far
# player - телепортация в режиме player
# base - телепортация в режиме base
menu:
  title: "&0&nРТП:"
  size: 54

  items:
    glass1:
      display_name: "&0 "
      description: [ ]
      material: BLACK_STAINED_GLASS_PANE
      model_data: 0
      enchantments:
        - UNBREAKING;1
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 0
        - 8
        - 45
        - 53

    back:
      display_name: "&cПерейти назад "
      description: [ ]
      material: ARROW
      slots:
        - 49
      function: close
      action: menu

    safe:
      display_name: "&aБезопасный РТП"
      description:
        - "&7Телепортация в безопасное место."
        - "&7Радиус &60-2500 блоков"
      material: EMERALD
      slots:
        - 20
      function: safe

    far:
      display_name: "&bДальний РТП"
      description:
        - "&7Телепортация на большие расстояния."
        - "&7Радиус &62000-10000 блоков"
      material: DIAMOND
      slots:
        - 22
      function: far

    player:
      display_name: "&eИгрок РТП"
      description:
        - "&7Телепортация вблизи случайного игрока."
        - "&7Рискованно, но интересно!"
        - "&7Радиус &650-120 блоков от игрока"
      material: PLAYER_HEAD
      slots:
        - 24
      function: player

    base:
      display_name: "&6База РТП"
      description:
        - "&7Телепортация рядом с базой."
        - "&7Радиус &650-150 блоков от региона"
      material: GOLD_INGOT
      slots:
        - 40
      function: base
