###########################################################
#
# Данный плагин был разработан студией EnumDev
# > Наша группа: https://vk.com/enumdev
# > Пользовательское соглашение: https://vk.com/topic-233774324_54052505
#
# Для заказа обратитесь в личные сообщения группы: https://vk.com/im?entrypoint=commu&sel=-233774324
#
###########################################################
settings:
  default-world: world  # мир по умолчанию
  disabled-worlds: # в случае использование функций в данных мирах, игрок будет перемещён в мир по умолчанию
    - spawn
    - pvp
    - duels

main:
  # enumrtp.safe.use - разрешить использование
  # enumrtp.safe.bypass - обход кулдауна
  safe:
    min-radius: 0  # Минимальная точка координат по модулю от 0 мира
    max-radius: 2500  # Максимальная точка координат по модулю от 0 мира
    allow-water-teleport: false  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 10  # Задержка на использование
    aliases:  # добавление возможности использовать телепорт без открывания меню, например /rtp safe
      - safe
      - safety
    messages:
      successful_teleport: "&6РТП &7» &fВы успешно телепортированы на координаты &6{coordinates}&f."
      block_cooldown: "&6РТП &7» &fВы сможете телепортироваться только через &6{seconds} сек."
      no_locations: "&6РТП &7» &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &7» &cВы не можете использоваь безопасную телепортацию!"


  # enumrtp.far.use - разрешить использование
  # enumrtp.far.bypass - обход кулдауна
  far:
    min-radius: 2000  # Минимальная точка координат по модулю от 0 мира
    max-radius: 10000  # Максимальная точка координат по модулю от 0 мира
    allow-water-teleport: false  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 60  # Задержка на использование
    aliases:
      - far
    messages:
      successful_teleport: "&6РТП &7» &fВы успешно телепортированы на координаты &6{coordinates}&f."
      block_cooldown: "&6РТП &7» &fВы сможете телепортироваться только через &6{seconds} сек."
      no_locations: "&6РТП &7» &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &7» &cВы не можете использоваь далёкую телепортацию!"

  # enumrtp.player.use - разрешить использование
  # enumrtp.player.bypass - обход кулдауна
  # enumrtp.player.ignore - запретить телепорт возле игрока
  player:
    min-radius: 50  # Минимальная точка по модулю от игрока
    max-radius: 120  # Максимальная точка координат по модулю от игрока
    allow-water-teleport: true  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    warnings: true  # Включить оповещения, отправляемые игроку, возле которого идёт телепорт
    warning-sound: BLOCK_BARREL_OPEN  # кастомный звук при предупреждении
    min-online: 1  # Минимальный онлайн на сервере для работы
    cooldown-seconds: 300  # Задержка на использование

    aliases:
      - player
      - near
    messages:
      successful_teleport: "&6РТП &7» &fВы успешно телепортированы на координаты &6{coordinates}&f рядом с игроком &6{player}&f."
      block_cooldown: "&6РТП &7» &fВы сможете телепортироваться только через &6{seconds} сек."
      no_locations: "&6РТП &7» &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &7» &cВы не можете телепортироваться рядом с игроками!"
      warning: "&c&lВНИМАНИЕ&8: &eВозле вас был телепортирован игрок, будьте осторожны!"


  # enumrtp.base.use - разрешить использование
  # enumrtp.base.bypass - обход кулдауна
  base:
    min-radius: 50  # Минимальная точка по модулю от региона
    max-radius: 150  # Максимальная точка координат по модулю от региона
    allow-water-teleport: true  # Разрешить телепорт на жидкие блоки
    always-up: true  # Всегда телепортировать на максимальную высоту, иначе возможен телепорт в пещеры
    cooldown-seconds: 3600  # Задержка на использование
    aliases:
      - base
    messages:
      successful_teleport: "&6РТП &7» &fВы успешно телепортированы на координаты &6{coordinates}&f рядом с регионом &6{region_name}&f."
      block_cooldown: "&6РТП &7» &fВы сможете телепортироваться только через &6{seconds} сек."
      no_locations: "&6РТП &7» &cЛокация не найдена, попробуйте ещё раз!"
      no_perm: "&6РТП &7» &cВы не можете телепортироваться рядом с базами!"

################################
######## Создание МЕНЮ #########
################################
# Доступные function:
# close - закрытие инвентаря
# safe - телепортация в режиме safe
# far - телепортация в режиме far
# player - телепортация в режиме player
# base - телепортация в режиме base
menu:
  title: "&0Рандомная телепортация:"
  size: 54

  items:
    glass1:
      display_name: "&0 "
      description: [ ]
      material: BLACK_STAINED_GLASS_PANE
      model_data: 0
      enchantments: [ ]
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 0
        - 8
        - 45
        - 53
    glass2:
      display_name: "&0 "
      description: [ ]
      material: PURPLE_STAINED_GLASS_PANE
      model_data: 0
      enchantments: [ ]
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 1
        - 7
        - 9
        - 17
        - 36
        - 44
        - 46
        - 52

    back:
      display_name: "&x&F&F&1&B&1&B← &x&F&F&0&9&0&9Н&x&F&F&0&0&0&0а&x&F&F&0&0&0&0з&x&F&F&0&0&0&0а&x&F&F&0&0&0&0д"
      description: [ ]
      material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWZjMjYxMWZiYWJlNGU3OTkwNjJmNmI0NzBhYzVhZTcyN2UzMmVmMDBkMmIxMTVkMzg2NTZlMzQxYzEyODkzNiJ9fX0=
      slots:
        - 49
      function: close
      action: menu

    safe:
      display_name: "&x&3&1&F&F&1&BБ&x&2&E&F&F&1&8л&x&2&A&F&F&1&6и&x&2&7&F&F&1&3ж&x&2&3&F&F&1&0н&x&2&0&F&F&0&Eя&x&1&C&F&F&0&Bя &x&1&5&F&F&0&5т&x&1&2&F&F&0&3е&x&0&E&F&F&0&0л&x&0&E&F&F&0&0е&x&0&E&F&F&0&0п&x&0&E&F&F&0&0о&x&0&E&F&F&0&0р&x&0&E&F&F&0&0т&x&0&E&F&F&0&0а&x&0&E&F&F&0&0ц&x&0&E&F&F&0&0и&x&0&E&F&F&0&0я"
      description:
        - ""
        - "&f Нажмите сюда для"
        - "&f Телепортации в &x&1&5&F&F&0&5безопасное место"
        - "&f Координаты от 0 до +-2500"
        - ""
      material: COMPASS
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 19
      function: safe

    far:
      display_name: "&x&5&F&E&2&C&5Д&x&5&7&E&5&C&5а&x&4&E&E&8&C&6л&x&4&6&E&B&C&6ь&x&3&D&E&E&C&7н&x&3&5&F&1&C&7я&x&2&C&F&3&C&7я &x&1&B&F&9&C&8т&x&1&3&F&C&C&9е&x&0&A&F&F&C&9л&x&0&A&F&F&C&9е&x&0&A&F&F&C&9п&x&0&A&F&F&C&9о&x&0&A&F&F&C&9р&x&0&A&F&F&C&9т&x&0&A&F&F&C&9а&x&0&A&F&F&C&9ц&x&0&A&F&F&C&9и&x&0&A&F&F&C&9я"
      description:
        - ""
        - "&f Нажмите сюда для"
        - "&f Телепортации в &x&1&B&F&9&C&8безопасное место"
        - "&f Координаты от 2000 до +-10000"
        - ""
      material: MAP
      enchantments:
        - UNBREAKING;1
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 21
      function: far

    player:
      display_name: "&x&E&4&3&A&9&6Т&x&E&6&3&6&9&6е&x&E&8&3&1&9&7л&x&E&A&2&D&9&7е&x&E&C&2&8&9&8п&x&E&E&2&4&9&8о&x&F&0&1&F&9&8р&x&F&3&1&B&9&9т&x&F&5&1&6&9&9а&x&F&7&1&2&9&9ц&x&F&9&0&D&9&Aи&x&F&B&0&9&9&Aя &x&F&F&0&0&9&Bв&x&F&F&0&0&9&Bо&x&F&F&0&0&9&Bз&x&F&F&0&0&9&Bл&x&F&F&0&0&9&Bе &x&F&F&0&0&9&Bи&x&F&F&0&0&9&Bг&x&F&F&0&0&9&Bр&x&F&F&0&0&9&Bо&x&F&F&0&0&9&Bк&x&F&F&0&0&9&Bо&x&F&F&0&0&9&Bв"
      description:
        - ""
        - "&f Нажмите сюда для"
        - "&f Телепортации возле &x&F&F&0&0&9&Bдругих игроков"
        - "&f Координаты от 50 до +-120 от игрока"
        - ""
      material: TOTEM_OF_UNDYING
      slots:
        - 23
      function: player

    base:
      display_name: "&x&9&8&6&3&E&7Т&x&9&6&5&E&E&9е&x&9&4&5&A&E&Bл&x&9&3&5&5&E&Eе&x&9&1&5&1&F&0п&x&8&F&4&C&F&2о&x&8&D&4&8&F&4р&x&8&B&4&3&F&6т&x&8&9&3&F&F&8а&x&8&8&3&A&F&Bц&x&8&6&3&6&F&Dи&x&8&4&3&1&F&Fя &x&8&4&3&1&F&Fв&x&8&4&3&1&F&Fо&x&8&4&3&1&F&Fз&x&8&4&3&1&F&Fл&x&8&4&3&1&F&Fе &x&8&4&3&1&F&Fб&x&8&4&3&1&F&Fа&x&8&4&3&1&F&Fз"
      description:
        - ""
        - "&f Нажмите сюда для"
        - "&f Телепортации возле &x&8&4&3&1&F&Fбаз игроков"
        - "&f Координаты от 50 до +-150 от базы"
        - ""
      material: CRYING_OBSIDIAN
      enchantments:
        - SHARPNESS;1
      hide_enchantments: true
      hide_effects: true
      hide_attributes: true
      slots:
        - 25
      function: base
